version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USERNAME=gubee
      - POSTGRES_PASSWORD=gubee
      - SCHEMA_DB=interview_service
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gubee
      - POSTGRES_USER=gubee
      - POSTGRES_PASSWORD=gubee
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
